import { defineCollection, z } from 'astro:content';

const pages = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    headline: z.string().optional(),
    subheadline: z.string().optional(),
    description: z.string().optional(),
    metaDescription: z.string().optional(),
    coverImage: z.string().optional(),
    draft: z.boolean().optional().default(false),
  }),
});

const writing = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    headline: z.string(),
    summary: z.string().optional(),
    keyword: z.string().optional(),
    metaDescription: z.string().optional(),
    coverImage: z.string().optional(),
    publishedAt: z.coerce.date(),
    tags: z.array(z.string()).optional().default([]),
    draft: z.boolean().optional().default(false),
  }),
});

const projects = defineCollection({
  type: 'data',
  schema: z.object({
    slug: z.string(),
    order: z.number(),
    number: z.string(),
    title: z.string(),
    client: z.string(),
    year: z.string(),
    role: z.string(),
    summary: z.string(),
    description: z.string(),
    tools: z.array(z.string()).default([]),
    skills: z.array(z.string()).default([]),
    coverImage: z.string().optional().default(""),
    images: z.array(z.string()).default([]),
    link: z.string().optional(),
    linkLabel: z.string().optional(),
    caseStudyLink: z.string().optional(),
    password: z.string().optional(),
  }),
});

const photoImageSchema = z.object({
  id: z.string().optional(),
  src: z.string(),
  alt: z.string(),
  width: z.number().optional(),
  height: z.number().optional(),
  caption: z.string().optional(),
  order: z.number().optional(),
  isCover: z.boolean().optional(),
});

const photoScoresSchema = z.object({
  scenery: z.number().min(1).max(10).optional(),
  food: z.number().min(1).max(10).optional(),
  cafe: z.number().min(1).max(10).optional(),
  relaxation: z.number().min(1).max(10).optional(),
  value: z.number().min(1).max(10).optional(),
  accessibility: z.number().min(1).max(10).optional(),
}).optional();

const photos = defineCollection({
  type: 'data',
  schema: z.object({
    slug: z.string(),
    order: z.number(),
    type: z.enum(["hotel", "restaurant", "cafe", "check-in"]).optional(),
    location: z.string(),
    name: z.string().optional(),
    city: z.string().optional(),
    district: z.string().optional(),
    country: z.string().optional(),
    province: z.string().optional(),
    region: z.string().optional(),
    headline: z.string(),
    subheadline: z.string().optional(),
    introduction: z.string().optional(),
    shortDescription: z.string().optional(),
    description: z.string().optional(),
    longDescription: z.string().optional(),
    travelFrom: z.string().optional(),
    travelTime: z.string().optional(),
    recommendedStay: z.string().optional(),
    bestMonths: z.string().optional(),
    budgetMin: z.number().optional(),
    budgetMax: z.number().optional(),
    budgetNote: z.string().optional(),
    transportation: z.array(z.string()).optional().default([]),
    suitableFor: z.array(z.string()).optional().default([]),
    overview: z.string().optional(),
    favoriteThings: z.string().optional(),
    whatIWouldDoAgain: z.string().optional(),
    editorialReview: z.string().optional(),
    personalRating: z.number().min(1).max(10).optional(),
    wouldReturn: z.enum(["definitely", "maybe", "unsure", "no"]).optional(),
    scores: photoScoresSchema,
    bestTimeOfDay: z.array(z.string()).optional().default([]),
    localTransport: z.array(z.string()).optional().default([]),
    weatherNote: z.string().optional(),
    crowdLevel: z.enum(["quiet", "moderate", "busy_weekends", "very_busy"]).optional(),
    travelDifficulty: z.enum(["very_easy", "easy", "moderate", "requires_preparation"]).optional(),
    travelTips: z.array(z.string()).optional().default([]),
    notFor: z.array(z.string()).optional().default([]),
    heroImage: photoImageSchema.optional(),
    images: z.array(photoImageSchema).default([]),
    googleMapsUrl: z.string().optional(),
    latitude: z.string().optional(),
    longitude: z.string().optional(),
    openingHours: z.string().optional(),
    priceRange: z.string().optional(),
    website: z.string().optional(),
    phone: z.string().optional(),
    bookingUrl: z.string().optional(),
    instagram: z.string().optional(),
    tags: z.array(z.string()).optional().default([]),
    featured: z.boolean().optional().default(false),
    published: z.boolean().optional().default(true),
    seoTitle: z.string().optional(),
    seoDescription: z.string().optional(),
    seoImage: z.string().optional(),
    relatedLocations: z.array(z.object({
      slug: z.string(),
      distance: z.string().optional(),
      category: z.string().optional(),
    })).optional().default([]),
    relatedArticles: z.array(z.object({
      slug: z.string(),
      title: z.string().optional(),
    })).optional().default([]),
    amenities: z.array(z.string()).optional().default([]),
    blocks: z.array(z.object({
      id: z.string(),
      type: z.string(),
      enabled: z.boolean(),
      title: z.string(),
      content: z.string().optional(),
    })).optional().default([]),
  }).passthrough(),
});

const gear = defineCollection({
  type: 'data',
  schema: z.object({
    title: z.string(),
    headline: z.string(),
    description: z.string(),
    sections: z.array(z.object({
      title: z.string(),
      slug: z.string(),
      headline: z.string().optional(),
      description: z.string(),
      image: z.string().optional(),
      items: z.array(z.object({
        name: z.string(),
        slug: z.string(),
        headline: z.string(),
        description: z.string(),
        image: z.string().optional(),
        url: z.string().optional(),
        tag: z.string().optional(),
      })).default([]),
    })).default([]),
  }),
});

export const collections = { pages, writing, projects, photos, gear };
